add documentation
feather-framework/feather-openapi-spec pull request #4
Opened 2024-05-17 17:40 UTC by GErP83

2024-05-17 18:31 UTC, tib commented on Package.swift
>          .package(url: "https://github.com/apple/swift-openapi-runtime", from: "1.0.0-alpha.1"),
We should use from: "1.0.0".

2024-05-21 07:11 UTC, mzpx approved these changes

2024-05-21 08:04 UTC, tib approved these changes

2024-05-21 08:07 UTC, tib requested changes

2024-05-21 08:07 UTC, tib commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-openapi-runtime", from: "1.4.0"),
This should be 1.0.0.

2024-05-21 09:13 UTC, viaszkadi approved these changes

2024-05-21 12:27 UTC, tib approved these changes

2024-05-21 12:31 UTC, merged